#pragma once
#include <string>
#include <unordered_map>

#include "minecraft/sounds/SoundTypes.h"

namespace JavaSoundIdMap {











inline int mapJavaSoundToLce(const std::string& name) {
    static const std::unordered_map<std::string, eSOUND_TYPE> kMap = {
        {"mob.chicken.say", eSoundType_MOB_CHICKEN_AMBIENT},
        {"mob.chicken", eSoundType_MOB_CHICKEN_AMBIENT},
        {"entity.chicken.ambient", eSoundType_MOB_CHICKEN_AMBIENT},
        {"entity.chicken.step", eSoundType_MOB_CHICKEN_STEP},
        {"mob.chicken.hurt", eSoundType_MOB_CHICKEN_HURT},
        {"entity.chicken.hurt", eSoundType_MOB_CHICKEN_HURT},
        {"mob.chicken.plop", eSoundType_MOB_CHICKENPLOP},
        {"mob.cow.say", eSoundType_MOB_COW_AMBIENT},
        {"mob.cow", eSoundType_MOB_COW_AMBIENT},
        {"mob.cow.hurt", eSoundType_MOB_COW_HURT},
        {"mob.pig.say", eSoundType_MOB_PIG_AMBIENT},
        {"mob.pig", eSoundType_MOB_PIG_AMBIENT},
        {"mob.pig.death", eSoundType_MOB_PIG_DEATH},
        {"mob.sheep.say", eSoundType_MOB_SHEEP_AMBIENT},
        {"mob.sheep", eSoundType_MOB_SHEEP_AMBIENT},
        
        {"mob.sheep.death", eSoundType_MOB_SHEEP_AMBIENT},
        {"mob.wolf.growl", eSoundType_MOB_WOLF_GROWL},
        {"mob.wolf.whine", eSoundType_MOB_WOLF_WHINE},
        {"mob.wolf.panting", eSoundType_MOB_WOLF_PANTING},
        {"mob.wolf.bark", eSoundType_MOB_WOLF_BARK},
        {"mob.wolf.hurt", eSoundType_MOB_WOLF_HURT},
        {"mob.wolf.death", eSoundType_MOB_WOLF_DEATH},
        {"mob.wolf.shake", eSoundType_MOB_WOLF_SHAKE},
        {"mob.blaze.breathe", eSoundType_MOB_BLAZE_BREATHE},
        {"mob.blaze.hit", eSoundType_MOB_BLAZE_HURT},
        {"mob.blaze.death", eSoundType_MOB_BLAZE_DEATH},
        {"mob.ghast.moan", eSoundType_MOB_GHAST_MOAN},
        {"mob.ghast.scream", eSoundType_MOB_GHAST_SCREAM},
        {"mob.ghast.death", eSoundType_MOB_GHAST_DEATH},
        {"mob.ghast.fireball", eSoundType_MOB_GHAST_FIREBALL},
        {"mob.ghast.charge", eSoundType_MOB_GHAST_CHARGE},
        {"mob.endermen.idle", eSoundType_MOB_ENDERMEN_IDLE},
        {"mob.endermen.hit", eSoundType_MOB_ENDERMEN_HIT},
        {"mob.endermen.death", eSoundType_MOB_ENDERMEN_DEATH},
        {"mob.endermen.portal", eSoundType_MOB_ENDERMEN_PORTAL},
        {"mob.zombiepig.zpig", eSoundType_MOB_ZOMBIEPIG_AMBIENT},
        {"mob.zombiepig.zpighurt", eSoundType_MOB_ZOMBIEPIG_HURT},
        {"mob.zombiepig.zpigdeath", eSoundType_MOB_ZOMBIEPIG_DEATH},
        {"mob.zombiepig.zpigangry", eSoundType_MOB_ZOMBIEPIG_ZPIGANGRY},
        {"mob.silverfish.say", eSoundType_MOB_SILVERFISH_AMBIENT},
        {"mob.silverfish.hit", eSoundType_MOB_SILVERFISH_HURT},
        {"mob.silverfish.kill", eSoundType_MOB_SILVERFISH_DEATH},
        {"mob.silverfish.step", eSoundType_MOB_SILVERFISH_STEP},
        {"mob.skeleton.say", eSoundType_MOB_SKELETON_AMBIENT},
        {"mob.skeleton", eSoundType_MOB_SKELETON_AMBIENT},
        {"mob.skeleton.hurt", eSoundType_MOB_SKELETON_HURT},
        {"mob.spider.say", eSoundType_MOB_SPIDER_AMBIENT},
        {"mob.spider.death", eSoundType_MOB_SPIDER_DEATH},
        {"mob.slime.small", eSoundType_MOB_SLIME_SMALL},
        {"mob.slime.attack", eSoundType_MOB_SLIME_ATTACK},
        
        {"mob.creeper.say", eSoundType_RANDOM_FUSE},
        {"mob.creeper.death", eSoundType_MOB_CREEPER_DEATH},
        {"mob.zombie.say", eSoundType_MOB_ZOMBIE_AMBIENT},
        {"mob.zombie.hurt", eSoundType_MOB_ZOMBIE_HURT},
        {"mob.zombie.death", eSoundType_MOB_ZOMBIE_DEATH},
        {"mob.zombie.wood", eSoundType_MOB_ZOMBIE_WOOD},
        {"mob.zombie.woodbreak", eSoundType_MOB_ZOMBIE_WOOD_BREAK},
        {"mob.zombie.metal", eSoundType_MOB_ZOMBIE_METAL},
        {"mob.magmacube.big", eSoundType_MOB_MAGMACUBE_BIG},
        {"mob.magmacube.small", eSoundType_MOB_MAGMACUBE_SMALL},
        {"mob.cat.purr", eSoundType_MOB_CAT_PURR},
        {"mob.cat.purreow", eSoundType_MOB_CAT_PURREOW},
        {"mob.cat.meow", eSoundType_MOB_CAT_MEOW},
        
        {"mob.cat.hiss", eSoundType_MOB_CAT_HIT},
        {"random.bow", eSoundType_RANDOM_BOW},
        {"random.bowhit", eSoundType_RANDOM_BOW_HIT},
        {"random.explode", eSoundType_RANDOM_EXPLODE},
        {"random.fizz", eSoundType_RANDOM_FIZZ},
        {"random.pop", eSoundType_RANDOM_POP},
        {"entity.item.pickup", eSoundType_RANDOM_POP},
        {"item.pickup", eSoundType_RANDOM_POP},
        {"random.fuse", eSoundType_RANDOM_FUSE},
        {"random.drink", eSoundType_RANDOM_DRINK},
        {"random.eat", eSoundType_RANDOM_EAT},
        {"random.burp", eSoundType_RANDOM_BURP},
        {"random.splash", eSoundType_RANDOM_SPLASH},
        {"random.click", eSoundType_RANDOM_CLICK},
        {"dig.glass", eSoundType_RANDOM_GLASS},
        {"random.orb", eSoundType_RANDOM_ORB},
        {"random.break", eSoundType_RANDOM_BREAK},
        {"random.chestopen", eSoundType_RANDOM_CHEST_OPEN},
        {"random.chestclosed", eSoundType_RANDOM_CHEST_CLOSE},
        {"random.door_open", eSoundType_RANDOM_DOOR_OPEN},
        {"random.door_close", eSoundType_RANDOM_DOOR_CLOSE},
        {"ambient.weather.rain", eSoundType_AMBIENT_WEATHER_RAIN},
        {"ambient.weather.thunder", eSoundType_AMBIENT_WEATHER_THUNDER},
        {"ambient.cave.cave", eSoundType_AMBIENT_CAVE_CAVE},
        {"portal.portal", eSoundType_PORTAL_PORTAL},
        {"portal.trigger", eSoundType_PORTAL_TRIGGER},
        {"portal.travel", eSoundType_PORTAL_TRAVEL},
        {"fire.ignite", eSoundType_FIRE_IGNITE},
        {"fire.fire", eSoundType_FIRE_FIRE},
        {"damage.hit", eSoundType_DAMAGE_HURT},
        {"game.player.hurt", eSoundType_DAMAGE_HURT},
        {"game.player.hurt.fall.small", eSoundType_DAMAGE_FALL_SMALL},
        {"game.player.hurt.fall.big", eSoundType_DAMAGE_FALL_BIG},
        {"game.hostile.hurt.fall.small", eSoundType_DAMAGE_FALL_SMALL},
        {"game.hostile.hurt.fall.big", eSoundType_DAMAGE_FALL_BIG},
        {"game.neutral.hurt.fall.small", eSoundType_DAMAGE_FALL_SMALL},
        {"game.neutral.hurt.fall.big", eSoundType_DAMAGE_FALL_BIG},
        {"damage.fallsmall", eSoundType_DAMAGE_FALL_SMALL},
        {"damage.fallbig", eSoundType_DAMAGE_FALL_BIG},
        {"note.harp", eSoundType_NOTE_HARP},
        {"note.bd", eSoundType_NOTE_BD},
        {"note.snare", eSoundType_NOTE_SNARE},
        {"note.hat", eSoundType_NOTE_HAT},
        {"note.bassattack", eSoundType_NOTE_BASSATTACK},
        {"note.bass", eSoundType_NOTE_BASSATTACK},
        
        {"note.pling", eSoundType_NOTE_HARP},
        {"tile.piston.in", eSoundType_TILE_PISTON_IN},
        {"tile.piston.out", eSoundType_TILE_PISTON_OUT},
        {"liquid.water", eSoundType_LIQUID_WATER},
        {"liquid.lavapop", eSoundType_LIQUID_LAVA_POP},
        {"liquid.lava", eSoundType_LIQUID_LAVA},
        {"step.stone", eSoundType_STEP_STONE},
        {"step.wood", eSoundType_STEP_WOOD},
        {"step.gravel", eSoundType_STEP_GRAVEL},
        {"step.grass", eSoundType_STEP_GRASS},
        {"step.metal", eSoundType_STEP_METAL},
        {"step.cloth", eSoundType_STEP_CLOTH},
        {"step.sand", eSoundType_STEP_SAND},
        {"mob.enderdragon.end", eSoundType_MOB_ENDERDRAGON_END},
        {"mob.enderdragon.growl", eSoundType_MOB_ENDERDRAGON_GROWL},
        {"mob.enderdragon.hit", eSoundType_MOB_ENDERDRAGON_HIT},
        {"mob.enderdragon.wings", eSoundType_MOB_ENDERDRAGON_MOVE},
        {"mob.irongolem.throw", eSoundType_MOB_IRONGOLEM_THROW},
        {"mob.irongolem.hit", eSoundType_MOB_IRONGOLEM_HIT},
        {"mob.irongolem.death", eSoundType_MOB_IRONGOLEM_DEATH},
        {"mob.irongolem.walk", eSoundType_MOB_IRONGOLEM_WALK},
        {"damage.thorns", eSoundType_DAMAGE_THORNS},
        {"random.anvil_break", eSoundType_RANDOM_ANVIL_BREAK},
        {"random.anvil_land", eSoundType_RANDOM_ANVIL_LAND},
        {"random.anvil_use", eSoundType_RANDOM_ANVIL_USE},
        {"mob.villager.haggle", eSoundType_MOB_VILLAGER_HAGGLE},
        {"mob.villager.idle", eSoundType_MOB_VILLAGER_IDLE},
        {"mob.villager.hit", eSoundType_MOB_VILLAGER_HIT},
        {"mob.villager.death", eSoundType_MOB_VILLAGER_DEATH},
        {"mob.villager.yes", eSoundType_MOB_VILLAGER_YES},
        {"mob.villager.no", eSoundType_MOB_VILLAGER_NO},
        {"mob.zombie.infect", eSoundType_MOB_ZOMBIE_INFECT},
        {"mob.zombie.unfect", eSoundType_MOB_ZOMBIE_UNFECT},
        {"mob.zombie.remedy", eSoundType_MOB_ZOMBIE_REMEDY},
        {"step.snow", eSoundType_STEP_SNOW},
        {"step.ladder", eSoundType_STEP_LADDER},
        {"dig.cloth", eSoundType_DIG_CLOTH},
        {"dig.grass", eSoundType_DIG_GRASS},
        {"dig.gravel", eSoundType_DIG_GRAVEL},
        {"dig.sand", eSoundType_DIG_SAND},
        {"dig.snow", eSoundType_DIG_SNOW},
        {"dig.stone", eSoundType_DIG_STONE},
        {"dig.wood", eSoundType_DIG_WOOD},
        {"fireworks.launch", eSoundType_FIREWORKS_LAUNCH},
        {"fireworks.blast", eSoundType_FIREWORKS_BLAST},
        {"fireworks.blast_far", eSoundType_FIREWORKS_BLAST_FAR},
        {"fireworks.largeBlast", eSoundType_FIREWORKS_LARGE_BLAST},
        {"fireworks.largeBlast_far", eSoundType_FIREWORKS_LARGE_BLAST_FAR},
        {"fireworks.twinkle", eSoundType_FIREWORKS_TWINKLE},
        {"fireworks.twinkle_far", eSoundType_FIREWORKS_TWINKLE_FAR},
        {"mob.bat.idle", eSoundType_MOB_BAT_IDLE},
        {"mob.bat.hurt", eSoundType_MOB_BAT_HURT},
        {"mob.bat.death", eSoundType_MOB_BAT_DEATH},
        {"mob.bat.takeoff", eSoundType_MOB_BAT_TAKEOFF},
        {"mob.wither.spawn", eSoundType_MOB_WITHER_SPAWN},
        {"mob.wither.idle", eSoundType_MOB_WITHER_IDLE},
        {"mob.wither.hurt", eSoundType_MOB_WITHER_HURT},
        {"mob.wither.death", eSoundType_MOB_WITHER_DEATH},
        {"mob.wither.shoot", eSoundType_MOB_WITHER_SHOOT},
        {"mob.cow.step", eSoundType_MOB_COW_STEP},
        {"step.cow", eSoundType_MOB_COW_STEP},
        {"mob.chicken.step", eSoundType_MOB_CHICKEN_STEP},
        {"step.chicken", eSoundType_MOB_CHICKEN_STEP},
        {"mob.pig.step", eSoundType_MOB_PIG_STEP},
        {"step.pig", eSoundType_MOB_PIG_STEP},
        {"mob.endermen.stare", eSoundType_MOB_ENDERMAN_STARE},
        {"mob.endermen.scream", eSoundType_MOB_ENDERMAN_SCREAM},
        {"mob.sheep.shear", eSoundType_MOB_SHEEP_SHEAR},
        {"mob.sheep.step", eSoundType_MOB_SHEEP_STEP},
        {"mob.skeleton.death", eSoundType_MOB_SKELETON_DEATH},
        {"mob.skeletondeath", eSoundType_MOB_SKELETON_DEATH},
        {"mob.skeleton.step", eSoundType_MOB_SKELETON_STEP},
        {"mob.spider.step", eSoundType_MOB_SPIDER_STEP},
        {"mob.wolf.step", eSoundType_MOB_WOLF_STEP},
        {"mob.zombie.step", eSoundType_MOB_ZOMBIE_STEP},
        {"liquid.swim", eSoundType_LIQUID_SWIM},
        {"game.player.swim", eSoundType_LIQUID_SWIM},
        {"game.player.swim.splash", eSoundType_RANDOM_SPLASH},
        {"game.hostile.swim.splash", eSoundType_RANDOM_SPLASH},
        {"game.neutral.swim.splash", eSoundType_RANDOM_SPLASH},
        {"game.neutral.swim", eSoundType_LIQUID_SWIM},
        {"game.hostile.swim", eSoundType_LIQUID_SWIM},
        {"mob.horse.land", eSoundType_MOB_HORSE_LAND},
        {"mob.horse.armor", eSoundType_MOB_HORSE_ARMOR},
        {"mob.horse.leather", eSoundType_MOB_HORSE_LEATHER},
        {"mob.horse.zombie.death", eSoundType_MOB_HORSE_ZOMBIE_DEATH},
        {"mob.horse.skeleton.death", eSoundType_MOB_HORSE_SKELETON_DEATH},
        {"mob.horse.donkey.death", eSoundType_MOB_HORSE_DONKEY_DEATH},
        {"mob.horse.death", eSoundType_MOB_HORSE_DEATH},
        {"mob.horse.zombie.hit", eSoundType_MOB_HORSE_ZOMBIE_HIT},
        {"mob.horse.skeleton.hit", eSoundType_MOB_HORSE_SKELETON_HIT},
        {"mob.horse.donkey.hit", eSoundType_MOB_HORSE_DONKEY_HIT},
        {"mob.horse.hit", eSoundType_MOB_HORSE_HIT},
        {"mob.horse.zombie.idle", eSoundType_MOB_HORSE_ZOMBIE_IDLE},
        {"mob.horse.skeleton.idle", eSoundType_MOB_HORSE_SKELETON_IDLE},
        {"mob.horse.donkey.idle", eSoundType_MOB_HORSE_DONKEY_IDLE},
        {"mob.horse.idle", eSoundType_MOB_HORSE_IDLE},
        {"mob.horse.donkey.angry", eSoundType_MOB_HORSE_DONKEY_ANGRY},
        {"mob.horse.angry", eSoundType_MOB_HORSE_ANGRY},
        {"mob.horse.gallop", eSoundType_MOB_HORSE_GALLOP},
        {"mob.horse.breathe", eSoundType_MOB_HORSE_BREATHE},
        {"mob.horse.wood", eSoundType_MOB_HORSE_WOOD},
        {"mob.horse.soft", eSoundType_MOB_HORSE_SOFT},
        {"mob.horse.jump", eSoundType_MOB_HORSE_JUMP},
        {"mob.witch.idle", eSoundType_MOB_WITCH_IDLE},
        {"mob.witch.hurt", eSoundType_MOB_WITCH_HURT},
        {"mob.witch.death", eSoundType_MOB_WITCH_DEATH},
        {"mob.slime.big", eSoundType_MOB_SLIME_BIG},
        {"mob.slime", eSoundType_MOB_SLIME},
        {"eat", eSoundType_EATING},
        {"random.levelup", eSoundType_RANDOM_LEVELUP},
    };
    auto it = kMap.find(name);
    return it != kMap.end() ? static_cast<int>(it->second) : -1;
}

}  
