#pragma once

#include "../WorldGen/Features/BasicTreeFeature.h"
#include "../WorldGen/Features/BirchFeature.h"
#include "../WorldGen/Features/CactusFeature.h"
#include "../WorldGen/Features/CaveFeature.h"
#include "../WorldGen/Features/ClayFeature.h"
#include "../WorldGen/Features/DeadBushFeature.h"
#include "../WorldGen/Features/Feature.h"
#include "../WorldGen/Features/FlowerFeature.h"
#include "../WorldGen/Features/HellFireFeature.h"
#include "../WorldGen/Features/HellPortalFeature.h"
#include "../WorldGen/Features/HellSpringFeature.h"
#include "../WorldGen/Features/HouseFeature.h"
#include "../WorldGen/Features/LakeFeature.h"
#include "../WorldGen/Features/LightGemFeature.h"
#include "../WorldGen/Features/MonsterRoomFeature.h"
#include "../WorldGen/Features/OreFeature.h"
#include "../WorldGen/Features/PineFeature.h"
#include "../WorldGen/Features/PumpkinFeature.h"
#include "../WorldGen/Features/ReedsFeature.h"
#include "../WorldGen/Features/SpringFeature.h"
#include "../WorldGen/Features/SpruceFeature.h"
#include "../WorldGen/Features/TallGrassFeature.h"
#include "../WorldGen/Features/TreeFeature.h"

#include "../WorldGen/Features/HugeMushroomFeature.h"
#include "../WorldGen/Features/SandFeature.h"
#include "../WorldGen/Features/SwampTreeFeature.h"
#include "../WorldGen/Features/BonusChestFeature.h"
#include "../WorldGen/Features/SpikeFeature.h"
#include "../WorldGen/Features/EndPodiumFeature.h"

#include "../WorldGen/Features/DesertWellFeature.h"
#include "../WorldGen/Features/MegaTreeFeature.h"
#include "../WorldGen/Features/VinesFeature.h"
#include "../WorldGen/Features/GroundBushFeature.h"