#pragma once

#include "../Network/Packets/AddEntityPacket.h"
#include "../Network/Packets/AddGlobalEntityPacket.h"
#include "../Network/Packets/AddMobPacket.h"
#include "../Network/Packets/AddPaintingPacket.h"
#include "../Network/Packets/AddPlayerPacket.h"
#include "../Network/Packets/AnimatePacket.h"
#include "../Network/Packets/AwardStatPacket.h"
#include "../Network/Packets/BlockRegionUpdatePacket.h"
#include "../Network/Packets/ChatPacket.h"
#include "../Network/Packets/ChunkTilesUpdatePacket.h"
#include "../Network/Packets/ChunkVisibilityPacket.h"
#include "../Network/Packets/ComplexItemDataPacket.h"
#include "../Network/Packets/ContainerAckPacket.h"
#include "../Network/Packets/ContainerClickPacket.h"
#include "../Network/Packets/ContainerClosePacket.h"
#include "../Network/Packets/ContainerOpenPacket.h"
#include "../Network/Packets/ContainerSetContentPacket.h"
#include "../Network/Packets/ContainerSetDataPacket.h"
#include "../Network/Packets/ContainerSetSlotPacket.h"
#include "../Network/Packets/DisconnectPacket.h"
#include "../Network/Packets/EntityActionAtPositionPacket.h"
#include "../Network/Packets/EntityEventPacket.h"
#include "../Network/Packets/ExplodePacket.h"
#include "../Network/Packets/GameEventPacket.h"
#include "../Network/Packets/InteractPacket.h"
#include "../Network/Packets/KeepAlivePacket.h"
#include "../Network/Packets/LevelEventPacket.h"
#include "../Network/Packets/LoginPacket.h"
#include "../Network/Packets/MoveEntityPacket.h"
#include "../Network/Packets/MoveEntityPacketSmall.h"
#include "../Network/Packets/MovePlayerPacket.h"
#include "../Network/Packets/Packet.h"
#include "../Network/Packets/PacketListener.h"
#include "../Network/Packets/PlayerActionPacket.h"
#include "../Network/Packets/PlayerCommandPacket.h"
#include "../Network/Packets/PlayerInputPacket.h"
#include "../Network/Packets/PreLoginPacket.h"
#include "../Network/Packets/RemoveEntitiesPacket.h"
#include "../Network/Packets/RespawnPacket.h"

#include "../Network/Packets/SetCarriedItemPacket.h"
#include "../Network/Packets/SetEntityDataPacket.h"
#include "../Network/Packets/SetEntityMotionPacket.h"
#include "../Network/Packets/SetEquippedItemPacket.h"
#include "../Network/Packets/SetHealthPacket.h"
#include "../Network/Packets/SetEntityLinkPacket.h"
#include "../Network/Packets/SetSpawnPositionPacket.h"
#include "../Network/Packets/SetTimePacket.h"
#include "../Network/Packets/SignUpdatePacket.h"
#include "../Network/Packets/TakeItemEntityPacket.h"
#include "../Network/Packets/TeleportEntityPacket.h"
#include "../Network/Packets/TileEventPacket.h"
#include "../Network/Packets/TileUpdatePacket.h"
#include "../Network/Packets/UseItemPacket.h"

// 1.8.2 Added
#include "../Network/Packets/AddExperienceOrbPacket.h"
#include "../Network/Packets/GetInfoPacket.h"
#include "../Network/Packets/PlayerInfoPacket.h"
#include "../Network/Packets/RemoveMobEffectPacket.h"
#include "../Network/Packets/SetCreativeModeSlotPacket.h"
#include "../Network/Packets/SetExperiencePacket.h"
#include "../Network/Packets/UpdateMobEffectPacket.h"

// 1.0.1 Added
#include "../Network/Packets/ContainerButtonClickPacket.h"
#include "../Network/Packets/TileEntityDataPacket.h"

// 1.1 Added (TU9)
#include "../Network/Packets/CustomPayloadPacket.h"

// 1.2.3
#include "../Network/Packets/RotateHeadPacket.h"

// 1.3.2
#include "../Network/Packets/ChatAutoCompletePacket.h"
#include "../Network/Packets/ClientCommandPacket.h"
#include "../Network/Packets/ClientInformationPacket.h"
#include "../Network/Packets/ClientProtocolPacket.h"
#include "../Network/Packets/LevelSoundPacket.h"
#include "../Network/Packets/PlayerAbilitiesPacket.h"
#include "../Network/Packets/ServerAuthDataPacket.h"
#include "../Network/Packets/TileDestructionPacket.h"

// 1.6.4
#include "../Network/Packets/LevelParticlesPacket.h"
#include "../Network/Packets/SetDisplayObjectivePacket.h"
#include "../Network/Packets/SetObjectivePacket.h"
#include "../Network/Packets/SetPlayerTeamPacket.h"
#include "../Network/Packets/SetScorePacket.h"
#include "../Network/Packets/TileEditorOpenPacket.h"
#include "../Network/Packets/UpdateAttributesPacket.h"

// 4J Added
#include "../Network/Packets/CraftItemPacket.h"
#include "../Network/Packets/TradeItemPacket.h"
#include "../Network/Packets/DebugOptionsPacket.h"
#include "../Network/Packets/ServerSettingsChangedPacket.h"
#include "../Network/Packets/TexturePacket.h"
#include "../Network/Packets/TextureAndGeometryPacket.h"
#include "../Network/Packets/ChunkVisibilityAreaPacket.h"
#include "../Network/Packets/UpdateProgressPacket.h"
#include "../Network/Packets/TextureChangePacket.h"
#include "../Network/Packets/TextureAndGeometryChangePacket.h"
#include "../Network/Packets/UpdateGameRuleProgressPacket.h"
#include "../Network/Packets/KickPlayerPacket.h"
#include "../Network/Packets/XZPacket.h"
#include "../Network/Packets/GameCommandPacket.h"
