#include "Consoles_SoundEngine.h"
#include "minecraft/sounds/SoundTypes.h"

const wchar_t* ConsoleSoundEngine::wchSoundNames[eSoundType_MAX] = {
    L"mob/chicken/chicken",        
    L"mob/chicken/chickenhurt",    
    L"mob/chicken/chickenplop",    
    L"mob/cow/say",                
    L"mob/cow/hurt",               
    L"mob/pig/pig",                
    L"mob/pig/pigdeath",           
    L"mob/sheep/sheep",            
    L"mob/wolf/growl",             
    L"mob/wolf/whine",             
    L"mob/wolf/panting",           
    L"mob/wolf/bark",              
    L"mob/wolf/hurt",              
    L"mob/wolf/death",             
    L"mob/wolf/shake",             
    L"mob/blaze/breathe",          
    L"mob/blaze/hit",              
    L"mob/blaze/death",            
    L"mob/ghast/moan",             
    L"mob/ghast/scream",           
    L"mob/ghast/death",            
    L"mob/ghast/fireball",         
    L"mob/ghast/charge",           
    L"mob/endermen/idle",          
    L"mob/endermen/hit",           
    L"mob/endermen/death",         
    L"mob/endermen/portal",        
    L"mob/zombiepig/zpig",         
    L"mob/zombiepig/zpighurt",     
    L"mob/zombiepig/zpigdeath",    
    L"mob/zombiepig/zpigangry",    
    L"mob/silverfish/say",         
    L"mob/silverfish/hit",         
    L"mob/silverfish/kill",        
    L"mob/silverfish/step",        
    L"mob/skeleton/skeleton",      
    L"mob/skeleton/skeletonhurt",  
    L"mob/spider/spider",          
    L"mob/spider/spiderdeath",     
    L"mob/slime/slime",            
    L"mob/slime/slimeattack",      
    L"mob/creeper/creeper",        
    L"mob/creeper/creeperdeath",   
    L"mob/zombie/zombie",          
    L"mob/zombie/zombiehurt",      
    L"mob/zombie/zombiedeath",     
    L"mob/zombie/wood",            
    L"mob/zombie/woodbreak",       
    L"mob/zombie/metal",           
    L"mob/magmacube/big",          
    L"mob/magmacube/small",        
    L"mob/cat/purr",               
    L"mob/cat/purreow",            
    L"mob/cat/meow",               
    
    L"mob/cat/hitt",  
                      
    
    
    
    
    L"random/bow",               
    L"random/bowhit",            
    L"random/explode",           
    L"random/fizz",              
    L"random/pop",               
    L"random/fuse",              
    L"random/drink",             
    L"random/eat",               
    L"random/burp",              
    L"random/splash",            
    L"random/click",             
    L"random/glass",             
    L"random/orb",               
    L"random/break",             
    L"random/chestopen",         
    L"random/chestclosed",       
    L"random/door_open",         
    L"random/door_close",        
    L"ambient/weather/rain",     
    L"ambient/weather/thunder",  
    L"ambient/cave/cave",  
    L"portal/portal",      
    
    L"portal/trigger",  
    L"portal/travel",   

    L"fire/ignite",       
    L"fire/fire",         
    L"damage/hit",        
    L"damage/fallsmall",  
    L"damage/fallbig",    
    L"note/harp",         
    L"note/bd",           
    L"note/snare",        
    L"note/hat",          
    L"note/bassattack",   
    L"tile/piston.in",    
    L"tile/piston.out",   
    L"liquid/water",      
    L"liquid/lavapop",    
    L"liquid/lava",       
    L"step/stone",        
    L"step/wood",         
    L"step/gravel",       
    L"step/grass",        
    L"step/metal",        
    L"step/cloth",        
    L"step/sand",         

    
    L"mob/enderdragon/end",    
    L"mob/enderdragon/growl",  
    L"mob/enderdragon/hit",    
    L"mob/enderdragon/wings",  
    L"mob/irongolem/throw",    
    L"mob/irongolem/hit",      
    L"mob/irongolem/death",    
    L"mob/irongolem/walk",     

    
    L"damage/thorns",        
    L"random/anvil_break",   
    L"random/anvil_land",    
    L"random/anvil_use",     
    L"mob/villager/haggle",  
    L"mob/villager/idle",    
    L"mob/villager/hit",     
    L"mob/villager/death",   
    L"mob/villager/yes",     
    L"mob/villager/no",      
    L"mob/zombie/infect",    
    L"mob/zombie/unfect",    
    L"mob/zombie/remedy",    
    L"step/snow",            
    L"step/ladder",          
    L"dig/cloth",            
    L"dig/grass",            
    L"dig/gravel",           
    L"dig/sand",             
    L"dig/snow",             
    L"dig/stone",            
    L"dig/wood",             

    
    L"fireworks/launch",           
    L"fireworks/blast",            
    L"fireworks/blast_far",        
    L"fireworks/large_blast",      
    L"fireworks/large_blast_far",  
    L"fireworks/twinkle",          
    L"fireworks/twinkle_far",      

    L"mob/bat/idle",     
    L"mob/bat/hurt",     
    L"mob/bat/death",    
    L"mob/bat/takeoff",  

    L"mob/wither/spawn",  
    L"mob/wither/idle",   
    L"mob/wither/hurt",   
    L"mob/wither/death",  
    L"mob/wither/shoot",  

    L"mob/cow/step",         
    L"mob/chicken/step",     
    L"mob/pig/step",         
    L"mob/enderman/stare",   
    L"mob/enderman/scream",  
    L"mob/sheep/shear",      
    L"mob/sheep/step",       
    L"mob/skeleton.death",   
    L"mob/skeleton/step",    
    L"mob/spider/step",      
    L"mob/wolf/step",        
    L"mob/zombie/step",      

    L"liquid/swim",  

    L"mob/horse/land",            
    L"mob/horse/armor",           
    L"mob/horse/leather",         
    L"mob/horse/zombie.death",    
    L"mob/horse/skeleton.death",  
    L"mob/horse/donkey.death",    
    L"mob/horse/death",           
    L"mob/horse/zombie.hit",      
    L"mob/horse/skeleton.hit",    
    L"mob/horse/donkey.hit",      
    L"mob/horse/hit",             
    L"mob/horse/zombie.idle",     
    L"mob/horse/skeleton.idle",   
    L"mob/horse/donkey.idle",     
    L"mob/horse/idle",            
    L"mob/horse/donkey.angry",    
    L"mob/horse/angry",           
    L"mob/horse/gallop",          
    L"mob/horse/breathe",         
    L"mob/horse/wood",            
    L"mob/horse/soft",            
    L"mob/horse/jump",            

    L"mob/witch/idle",   
                         
    L"mob/witch/hurt",   
                         
    L"mob/witch/death",  
                         

    L"mob/slime/big",    
    L"mob/slime/small",  

    L"eating",          
    L"random/levelup",  

    
    
    
    L"fire/new_ignite",
};

const wchar_t* ConsoleSoundEngine::wchUISoundNames[eSFX_MAX] = {
    L"back", L"craft", L"craftfail", L"focus", L"press", L"scroll",
};
