#pragma once

#include "Minecraft.Client/Common/src/UI/All Platforms/UIEnums.h"
#include "Minecraft.Client/Common/src/UI/All Platforms/UIStructs.h"
#include "Minecraft.Client/Common/src/UI/Components/UIComponent_Chat.h"
#include "Minecraft.Client/Common/src/UI/Components/UIComponent_DebugUIConsole.h"
#include "Minecraft.Client/Common/src/UI/Components/UIComponent_DebugUIMarketingGuide.h"
#include "Minecraft.Client/Common/src/UI/Components/UIComponent_Logo.h"
#include "Minecraft.Client/Common/src/UI/Components/UIComponent_MenuBackground.h"
#include "Minecraft.Client/Common/src/UI/Components/UIComponent_Panorama.h"
#include "Minecraft.Client/Common/src/UI/Components/UIComponent_PressStartToPlay.h"
#include "Minecraft.Client/Common/src/UI/Components/UIComponent_Tooltips.h"
#include "Minecraft.Client/Common/src/UI/Components/UIComponent_TutorialPopup.h"
#include "Minecraft.Client/Common/src/UI/Components/UIScene_HUD.h"
#include "Minecraft.Client/Common/src/UI/Controls/UIControl.h"
#include "Minecraft.Client/Common/src/UI/Controls/UIControl_Base.h"
#include "Minecraft.Client/Common/src/UI/Controls/UIControl_BeaconEffectButton.h"
#include "Minecraft.Client/Common/src/UI/Controls/UIControl_BitmapIcon.h"
#include "Minecraft.Client/Common/src/UI/Controls/UIControl_Button.h"
#include "Minecraft.Client/Common/src/UI/Controls/UIControl_ButtonList.h"
#include "Minecraft.Client/Common/src/UI/Controls/UIControl_CheckBox.h"
#include "Minecraft.Client/Common/src/UI/Controls/UIControl_Cursor.h"
#include "Minecraft.Client/Common/src/UI/Controls/UIControl_DLCList.h"
#include "Minecraft.Client/Common/src/UI/Controls/UIControl_DynamicLabel.h"
#include "Minecraft.Client/Common/src/UI/Controls/UIControl_EnchantmentBook.h"
#include "Minecraft.Client/Common/src/UI/Controls/UIControl_EnchantmentButton.h"
#include "Minecraft.Client/Common/src/UI/Controls/UIControl_HTMLLabel.h"
#include "Minecraft.Client/Common/src/UI/Controls/UIControl_Label.h"
#include "Minecraft.Client/Common/src/UI/Controls/UIControl_LeaderboardList.h"
#include "Minecraft.Client/Common/src/UI/Controls/UIControl_MinecraftHorse.h"
#include "Minecraft.Client/Common/src/UI/Controls/UIControl_MinecraftPlayer.h"
#include "Minecraft.Client/Common/src/UI/Controls/UIControl_PlayerList.h"
#include "Minecraft.Client/Common/src/UI/Controls/UIControl_PlayerSkinPreview.h"
#include "Minecraft.Client/Common/src/UI/Controls/UIControl_Progress.h"
#include "Minecraft.Client/Common/src/UI/Controls/UIControl_SaveList.h"
#include "Minecraft.Client/Common/src/UI/Controls/UIControl_Slider.h"
#include "Minecraft.Client/Common/src/UI/Controls/UIControl_SlotList.h"
#include "Minecraft.Client/Common/src/UI/Controls/UIControl_SpaceIndicatorBar.h"
#include "Minecraft.Client/Common/src/UI/Controls/UIControl_TextInput.h"
#include "Minecraft.Client/Common/src/UI/Controls/UIControl_TexturePackList.h"
#include "Minecraft.Client/Common/src/UI/Scenes/Debug/UIScene_DebugCreateSchematic.h"
#include "Minecraft.Client/Common/src/UI/Scenes/Debug/UIScene_DebugOptions.h"
#include "Minecraft.Client/Common/src/UI/Scenes/Debug/UIScene_DebugOverlay.h"
#include "Minecraft.Client/Common/src/UI/Scenes/Debug/UIScene_DebugSetCamera.h"
#include "Minecraft.Client/Common/src/UI/Scenes/Frontend Menu screens/UIScene_CreateWorldMenu.h"
#include "Minecraft.Client/Common/src/UI/Scenes/Frontend Menu screens/UIScene_DLCMainMenu.h"
#include "Minecraft.Client/Common/src/UI/Scenes/Frontend Menu screens/UIScene_DLCOffersMenu.h"
#include "Minecraft.Client/Common/src/UI/Scenes/Frontend Menu screens/UIScene_EULA.h"
#include "Minecraft.Client/Common/src/UI/Scenes/Frontend Menu screens/UIScene_Intro.h"
#include "Minecraft.Client/Common/src/UI/Scenes/Frontend Menu screens/UIScene_JoinMenu.h"
#include "Minecraft.Client/Common/src/UI/Scenes/Frontend Menu screens/UIScene_LaunchMoreOptionsMenu.h"
#include "Minecraft.Client/Common/src/UI/Scenes/Frontend Menu screens/UIScene_LeaderboardsMenu.h"
#include "Minecraft.Client/Common/src/UI/Scenes/Frontend Menu screens/UIScene_LoadMenu.h"
#include "Minecraft.Client/Common/src/UI/Scenes/Frontend Menu screens/UIScene_LoadOrJoinMenu.h"
#include "Minecraft.Client/Common/src/UI/Scenes/Frontend Menu screens/UIScene_MainMenu.h"
#include "Minecraft.Client/Common/src/UI/Scenes/Frontend Menu screens/UIScene_NewUpdateMessage.h"
#include "Minecraft.Client/Common/src/UI/Scenes/Frontend Menu screens/UIScene_SaveMessage.h"
#include "Minecraft.Client/Common/src/UI/Scenes/Frontend Menu screens/UIScene_TrialExitUpsell.h"
#include "Minecraft.Client/Common/src/UI/Scenes/Help & Options/UIScene_ControlsMenu.h"
#include "Minecraft.Client/Common/src/UI/Scenes/Help & Options/UIScene_Credits.h"
#include "Minecraft.Client/Common/src/UI/Scenes/Help & Options/UIScene_HelpAndOptionsMenu.h"
#include "Minecraft.Client/Common/src/UI/Scenes/Help & Options/UIScene_HowToPlay.h"
#include "Minecraft.Client/Common/src/UI/Scenes/Help & Options/UIScene_HowToPlayMenu.h"
#include "Minecraft.Client/Common/src/UI/Scenes/Help & Options/UIScene_LanguageSelector.h"
#include "Minecraft.Client/Common/src/UI/Scenes/Help & Options/UIScene_ReinstallMenu.h"
#include "Minecraft.Client/Common/src/UI/Scenes/Help & Options/UIScene_SettingsAudioMenu.h"
#include "Minecraft.Client/Common/src/UI/Scenes/Help & Options/UIScene_SettingsControlMenu.h"
#include "Minecraft.Client/Common/src/UI/Scenes/Help & Options/UIScene_SettingsGraphicsMenu.h"
#include "Minecraft.Client/Common/src/UI/Scenes/Help & Options/UIScene_SettingsMenu.h"
#include "Minecraft.Client/Common/src/UI/Scenes/Help & Options/UIScene_SettingsOptionsMenu.h"
#include "Minecraft.Client/Common/src/UI/Scenes/Help & Options/UIScene_SettingsUIMenu.h"
#include "Minecraft.Client/Common/src/UI/Scenes/Help & Options/UIScene_SkinSelectMenu.h"
#include "Minecraft.Client/Common/src/UI/Scenes/In-Game Menu Screens/Containers/UIScene_AbstractContainerMenu.h"
#include "Minecraft.Client/Common/src/UI/Scenes/In-Game Menu Screens/Containers/UIScene_AnvilMenu.h"
#include "Minecraft.Client/Common/src/UI/Scenes/In-Game Menu Screens/Containers/UIScene_BeaconMenu.h"
#include "Minecraft.Client/Common/src/UI/Scenes/In-Game Menu Screens/Containers/UIScene_BrewingStandMenu.h"
#include "Minecraft.Client/Common/src/UI/Scenes/In-Game Menu Screens/Containers/UIScene_ContainerMenu.h"
#include "Minecraft.Client/Common/src/UI/Scenes/In-Game Menu Screens/Containers/UIScene_CreativeMenu.h"
#include "Minecraft.Client/Common/src/UI/Scenes/In-Game Menu Screens/Containers/UIScene_DispenserMenu.h"
#include "Minecraft.Client/Common/src/UI/Scenes/In-Game Menu Screens/Containers/UIScene_EnchantingMenu.h"
#include "Minecraft.Client/Common/src/UI/Scenes/In-Game Menu Screens/Containers/UIScene_FireworksMenu.h"
#include "Minecraft.Client/Common/src/UI/Scenes/In-Game Menu Screens/Containers/UIScene_FurnaceMenu.h"
#include "Minecraft.Client/Common/src/UI/Scenes/In-Game Menu Screens/Containers/UIScene_HopperMenu.h"
#include "Minecraft.Client/Common/src/UI/Scenes/In-Game Menu Screens/Containers/UIScene_HorseInventoryMenu.h"
#include "Minecraft.Client/Common/src/UI/Scenes/In-Game Menu Screens/Containers/UIScene_InventoryMenu.h"
#include "Minecraft.Client/Common/src/UI/Scenes/In-Game Menu Screens/Containers/UIScene_TradingMenu.h"
#include "Minecraft.Client/Common/src/UI/Scenes/In-Game Menu Screens/UIScene_CraftingMenu.h"
#include "Minecraft.Client/Common/src/UI/Scenes/In-Game Menu Screens/UIScene_DeathMenu.h"
#include "Minecraft.Client/Common/src/UI/Scenes/In-Game Menu Screens/UIScene_EndPoem.h"
#include "Minecraft.Client/Common/src/UI/Scenes/In-Game Menu Screens/UIScene_InGameHostOptionsMenu.h"
#include "Minecraft.Client/Common/src/UI/Scenes/In-Game Menu Screens/UIScene_InGameInfoMenu.h"
#include "Minecraft.Client/Common/src/UI/Scenes/In-Game Menu Screens/UIScene_InGamePlayerOptionsMenu.h"
#include "Minecraft.Client/Common/src/UI/Scenes/In-Game Menu Screens/UIScene_PauseMenu.h"
#include "Minecraft.Client/Common/src/UI/Scenes/In-Game Menu Screens/UIScene_SignEntryMenu.h"
#include "Minecraft.Client/Common/src/UI/Scenes/In-Game Menu Screens/UIScene_TeleportMenu.h"
#include "Minecraft.Client/Common/src/UI/Scenes/UIScene_ConnectingProgress.h"
#include "Minecraft.Client/Common/src/UI/Scenes/UIScene_FullscreenProgress.h"
#include "Minecraft.Client/Common/src/UI/Scenes/UIScene_Keyboard.h"
#include "Minecraft.Client/Common/src/UI/Scenes/UIScene_MessageBox.h"
#include "Minecraft.Client/Common/src/UI/Scenes/UIScene_QuadrantSignin.h"
#include "Minecraft.Client/Common/src/UI/Scenes/UIScene_Timer.h"
#include "UIBitmapFont.h"
#include "UIController.h"
#include "UIGroup.h"
#include "UILayer.h"
#include "UIScene.h"
#include "UITTFFont.h"