#pragma once

#include "ArmorDyeRecipe.h"
#include "ArmorRecipes.h"
#include "ClothDyeRecipes.h"
#include "FireworksRecipe.h"
#include "FoodRecipes.h"
#include "FurnaceRecipes.h"
#include "OreRecipes.h"
#include "Recipes.h"
#include "Recipy.h"
#include "ShapedRecipy.h"
#include "ShapelessRecipy.h"
#include "StructureRecipes.h"
#include "ToolRecipes.h"
#include "WeaponRecipes.h"