name: Format Check (Linux, x86-64)

on: [push, pull_request]
  paths:
    - '**.cpp'
    - '**.h'
    - '**.c'
    - '**.cc'
    - '**.cxx'
    - '**.hh'
    - '**.hpp'
    - '**.hxx'
    - '**.inl'
    - "**meson.build"
    - "flake.nix"
    - ".clang-format"
    - '.github/workflows/build-linux.yml'
    - ".github/scripts/check-clang-format.sh"

jobs:
  formatting-check:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v6
        with:
          fetch-depth: 0

      - name: Run clang-format style check
        uses: jidicula/clang-format-action@v4.18.0
        with:
          # keep this in line with the flake
          clang-format-version: "21"
